# Generated by Django 4.2.7 on 2025-04-14 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='token_number',
            field=models.CharField(default='11a1ef', max_length=10, unique=True),
        ),
    ]
